### ISSUE TITLE
[FEAT] Additional NVR Options

### ISSUE THREAD

**Issue by linedpaper** [skrashevich/double-take#108]
I would love to see additional NVR options than Frigate.  I am using Scrypted.  I can already publish mqtt or have webhooks from the app, just cannot figure out how to get those working with double-take.  I think others already have this one working so it's possibly just a matter of figuring out the correct configuration for Scrypted at least.

**Comment by DrSpaldo** [comment]
@linedpaper so how exactly is your system set up?

**Comment by skrashevich** [comment]
you can use cameras[].snapshot.url configuration option for target double-take to scrypted, and [HTTP REST API](https://double-take.site) for trigger recognition from scrypted

**Comment by maumi** [comment]
Thanks for the hint. 
maybe anyone cares later:
I ended up with directly call double-take api and push photos from home assistant to double-take. 
In my use case it is a doorbell with face recognition and opening door so I have a fixed Trigger I can use and don't need frigate or scrypted for that

**Comment by skrashevich** [comment]
can you share you implementation to others?

**Comment by maumi** [comment]
Sure. But it is really specific. 
In textual form I make the following steps
-Take snapshot with home assistant (could be also done directly with ffmpeg)
-post snapshot to double-take

The snapshot is taken in HA with camera.snapshot and putted on file system of HA. 

The post is done by curl and in HA as

shell_command:
  klingel_double: curl --location 'http://192.168.1.XX:3000/api/recognize/upload' --form 'files[]=@"/file/to/snapshot.jpg"'

The trigger work itself than is just triggered by motion sensor or press of doorbell and than snapshot is taken and curl command is called. 
In my case in a 5 times loop to better catch a good snapshot.
