### ISSUE TITLE
[BUG] Sublabels not returned in Frigate/[ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by popperwin** [skrashevich/double-take#117]
**Describe the bug**
Sub_labels are not showing up in Frigate, but in double take I can see the matching without any issues. 
Another issue happens at the same time in the logs.
Same configuration of frigate and double-take tested on version 1.13.10, it's working fine.

```
2023-09-18 18:50:33 error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
2023-09-18 18:50:33     at new NodeError (node:internal/errors:387:5)
2023-09-18 18:50:33     at ServerResponse.setHeader (node:_http_outgoing:644:11)
2023-09-18 18:50:33     at ServerResponse.header (/double-take/api/node_modules/express/lib/response.js:794:10)
2023-09-18 18:50:33     at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:174:12)
2023-09-18 18:50:33     at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
2023-09-18 18:50:33     at ServerResponse.json (/double-take/api/node_modules/express/lib/response.js:278:15)
2023-09-18 18:50:33     at ServerResponse.send (/double-take/api/node_modules/express/lib/response.js:162:21)
2023-09-18 18:50:33     at ServerResponse.res.send (/double-take/api/src/middlewares/respond.js:41:18)
2023-09-18 18:50:33     at /double-take/api/src/app.js:46:38
2023-09-18 18:50:33     at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20)
```

**Version of Double Take**
`sha-f7b7bca (1.13.11.3)`

**Expected behavior**
Sub-labels should arrives in frigate

**Screenshots**

**Hardware**
 - Architecture or platform:  x64
 - OS: [e.g. Ubuntu, macOS, Windows] Windows 10
 - Browser (if applicable) [e.g. Chrome, Safari]: Chrome
 - Docker image (if applicable) [e.g. skrashevich/double-take:latest] : skrashevich/double-take:latest skrashevich/double-take:v1.13.11.3

**Additional context**

**Comment by medenlin** [comment]
I have a same bug on 1.13.11.4 + frigate 0.13.0-9A4F970. Also on 1.13.11.4 Matches page not auto-update.
But 1.13.10 works fine.

**Comment by emelarnz** [comment]
I have the same bug on 1.13.11.3 + frigate 0.13.0-0858859. As @medenlin said, 1.13.10 works fine. Should we open a new bug or can this one be re-opened?

**Comment by pmuir** [comment]
Happening for me too. Reverting to 1.13.10 removes the error for me.

**Comment by Mincka** [comment]
Version v1.13.11.5 release yesterday should fix this. I'm updating my container right now. Thank you.

**Comment by Mincka** [comment]
Actually, not sure if really fixed because I don't get the error message but the sublabels are not updated in Frigate despite person matching.

```
23-11-04 09:33:56 info: undefined
23-11-04 09:33:59 info: done processing Frigate_Sonnette: 1699090435.103491-2wamdt in 4.19 sec
23-11-04 09:33:59 info: {
  id: '1699090435.103491-2wamdt',
  duration: 4.19,
  timestamp: '2023-11-04T09:33:59.695Z',
  attempts: 15,
  camera: 'Frigate_Sonnette',
  zones: [],
  counts: { person: 1, match: 1, miss: 2, unknown: -2 },
  matches: [
    {
      name: 'morgane',
      confidence: 90.35,
      match: true,
      box: [Object],
      type: 'latest',
      duration: 0.45,
      detector: 'compreface',
      filename: '7daa6b9b-34ab-4a4e-9181-ae34d86cf15a.jpg'
    }
  ],
  misses: [
    {
      name: 'julien',
      confidence: 62.54,
      match: false,
      box: [Object],
      checks: [Array],
      type: 'latest',
      duration: 0.35,
      detector: 'compreface',
      filename: '489ba860-24d0-4f02-96ed-335169ba4665.jpg'
    },
    {
      name: 'morgane',
      confidence: 84.83,
      match: false,
      box: [Object],
      checks: [Array],
      type: 'latest',
      duration: 0.64,
      detector: 'compreface',
      filename: '54ac28df-25f3-4853-ac5f-6b0d72527943.jpg'
    }
  ],
  unknowns: []
}
```

No changes in DoubleTake config:
```
frigate:
  url: http://10.0.0.84:5000/
  update_sub_labels: true
```

**Comment by Nafania** [comment]
@Mincka same for me. Error in logs is gone but sublabels stopped being updated with the latest release

**Comment by Mincka** [comment]
Can we reopen this?

**Comment by tgmos** [comment]
Have the same issue with newer versions, they dont post back to frigate,  however version 1.13.10 post "['name', none]" back to Frigate.
