### ISSUE TITLE
[BUG] Pictures in portrait mode are not rendered correctly. Maybe causing an issue with training

### ISSUE THREAD

**Issue by ultratoto14** [skrashevich/double-take#118]
I went from original double-take to yours and found out that all my pictures coming from my phone (Samsung Galaxy Note 20 Ultra) in portrait mode are displayed in landscape mode in the UI.

I thought it was not a problem but when I was trying CodeProject.AI, the logs shows no face detected on these images, Just added one picture taken in landscape mode and CodeProject.AI detected the faces.

**Version of Double Take**
1.13.11.3

**Expected behavior**
Portrait photo should be sent/viewed as portrait

**Screenshots**
![2023-09-22_15-23-20](https://github.com/skrashevich/double-take/assets/3328573/17cc9376-d3f7-4b96-9e37-217b5cb76888)

**Hardware**
 - amd64 + GPU
 - Qnap NAS OS
 - Chrome
 - skrashevich/double-take:latest

**Comment by skrashevich** [comment]
Do you upload photos directly from your phone, or do you transfer them to PC first?

**Comment by ultratoto14** [comment]
Hi, I uploaded from phone directly, using google chrome.

**Comment by skrashevich** [comment]
please, provide an example of problem photo file

**Comment by ultratoto14** [comment]
Here is an example picture
![20230925_085408](https://github.com/skrashevich/double-take/assets/3328573/f765db2a-834b-4289-8379-db8d92b2806c)
And the view in double-take:
![Screenshot_20230925_085514_Chrome](https://github.com/skrashevich/double-take/assets/3328573/79c1acad-eee4-43c3-b2a4-e5dffb4f4ea1)

**Comment by skrashevich** [comment]
thx. I was able to reproduce this issue. fixed in current latest beta build. will be included in next release

**Comment by ultratoto14** [comment]
Hi @skrashevich , just tested the latest beta and it seems that it works most of the time. 
When I tried to retrain all the files sent from my phone, it's really slow to process and most of them received a 413 from compreface:

``
172.29.36.1 - - [25/Sep/2023:06:59:40 -0700] "POST /api/v1/recognition/faces?subject=emile HTTP/1.1" 201 91 "-" "axios/1.5.0"
2023/09/25 07:00:29 [error] 106#106: *651862 client intended to send too large body: 5338079 bytes, client: 172.29.36.1, server: ui, request: "POST /api/v1/recognition/faces?subject=emile HTTP/1.1", host: "192.168.15.4:8000"
172.29.36.1 - - [25/Sep/2023:07:00:30 -0700] "POST /api/v1/recognition/faces?subject=emile HTTP/1.1" 413 192 "-" "axios/1.5.0"
2023/09/25 07:03:16 [error] 106#106: *651863 client intended to send too large body: 5206261 bytes, client: 172.29.36.1, server: ui, request: "POST /api/v1/recognition/faces?subject=jade HTTP/1.1", host: "192.168.15.4:8000"
172.29.36.1 - - [25/Sep/2023:07:03:16 -0700] "POST /api/v1/recognition/faces?subject=jade HTTP/1.1" 413 192 "-" "axios/1.5.0"
2023/09/25 07:03:16 [error] 106#106: *651864 client intended to send too large body: 5139979 bytes, client: 172.29.36.1, server: ui, request: "POST /api/v1/recognition/faces?subject=jade HTTP/1.1", host: "192.168.15.4:8000"
172.29.36.1 - - [25/Sep/2023:07:03:16 -0700] "POST /api/v1/recognition/faces?subject=jade HTTP/1.1" 413 192 "-" "axios/1.5.0"
2023/09/25 07:03:16 [error] 106#106: *651865 client intended to send too large body: 5130935 bytes, client: 172.29.36.1, server: ui, request: "POST /api/v1/recognition/faces?subject=jade HTTP/1.1", host: "192.168.15.4:8000"
172.29.36.1 - - [25/Sep/2023:07:03:16 -0700] "POST /api/v1/recognition/faces?subject=jade HTTP/1.1" 413 192 "-" "axios/1.5.0"
`` 

As it seems that you changed the image orientation, the picture data size became too big.

**Comment by skrashevich** [comment]
it's not a compreface problem. look like you have nginx in front of compreface?

**Comment by skrashevich** [comment]
this is limitation in compreface single-image: https://github.com/exadel-inc/CompreFace/blob/4d826e53bdbe82c2a2ed2229aa27785cdf732247/custom-builds/Single-Docker-File/nginx.conf#L19

for increase this limit you can, for example, [download nginx.conf](https://raw.githubusercontent.com/exadel-inc/CompreFace/master/custom-builds/Single-Docker-File/nginx.conf) to you host, change this property and mount it to compreface container (`docker run .... -v path_to_modified_nginxconf:/etc/nginx/conf.d/nginx.conf`)

anyway, this is compreface issue, not double-take

**Comment by atv2016** [comment]
> thx. I was able to reproduce this issue. fixed in current latest beta build. will be included in next release

@skrashevich I have the same issue all of a sudden (auto-rotation). Was wondering how this happened, never had an issue with it before. Did we include some new dependancy or something?

Thanks for fixing.

How do i install the beta from the add-on store ? Anyway of doing this ? Or can we push the new release?

**Comment by skrashevich** [comment]
fixed in v1.13.11.4 release
