### ISSUE TITLE
[BUG] Gotify ?

### ISSUE THREAD

**Issue by Nonobis** [skrashevich/double-take#125]
**Describe the bug**
Maybe not a bug ? I am trying to send notification to my Gotify server. I am not using Home Assistant.

**Version of Double Take**
1.13.11.3

**Expected behavior**
I want to received a notification every time a face is received on double take (identified or not)

**Hardware**
LXC Container on Proxmox on Docker
Frigate/Double Take/Coral AI Server
Docker Image : skrashevich/double-take:latest

**Additional context**

Declared in config file like this

notify:
  gotify: 
   url: !secret gotify_url
   token: !secret gotify_key

**Comment by skrashevich** [comment]
Try to set in config:

'''
notify:
  only_unknown: false
'''

**Comment by Nonobis** [comment]
Thanks i have updated my config.
It's a remote home so i can confirm if it's working in a few hours if event a captured....I will closing ticket if it's working :)

**Comment by skrashevich** [comment]
this is well-known bug in 1.13.11.3 release. will be fixed in 1.13.11.4
