### ISSUE TITLE
[FEAT] Configurable Device Tracker Reset Duration

### ISSUE THREAD

**Issue by joeblack2k** [skrashevich/double-take#131]
**Feature Request: Configurable Device Tracker Reset Duration**

**Problem:**
Currently, the device tracker in Double Take sets the "home" state for 30 minutes before changing back to "away." While this default behavior works for many scenarios, there are cases, such as a doorbell application, where users often return within a shorter timeframe, making the 30-minute duration less suitable.

**Solution:**
I propose adding a configuration option in Double Take that allows users to set a custom duration for the device tracker to reset its state. Specifically, it would be beneficial to have the ability to configure the duration after which the device tracker state transitions from "home" to "away" after the last facial recognition detection. For example, having an option to set the reset duration to 10 seconds or any other desired timeframe would greatly enhance the software's flexibility and adaptability to various use cases.

**Additional Context:**
In my specific use case, the doorbell application, users typically return within a minute. To address this, I have implemented a workaround in Home Assistant by setting the MQTT topic homeassistant/sensor/double-take/joeblack2k/ "camera" state to "none" after 10 seconds when there are no new detections. 

However, having this functionality integrated (setting camera to none in x seconds/minutes preferably configurable) into Double Take itself would streamline the process and make the user experience more intuitive and efficient. (included screenshot)

Thank you for considering this feature request. I believe this customization option would significantly improve the usability of Double Take for users with specific use cases like mine.
<img width="711" alt="Screenshot 2023-10-01 at 20 44 24" src="https://github.com/skrashevich/double-take/assets/3456102/6608805c-7a1d-4616-a916-6f68fc6b5d99">

**Comment by Mincka** [comment]
Thank for you that.
I think there's an indentation mistake for `device_tracker_timeout` in [README.md](https://github.com/skrashevich/double-take/blob/main/README.md). It appears to be under `events:` and that's I tried first, but it did not work and then I saw in the commit that it should be under `frigate:`. Then it works fine.
