### ISSUE TITLE
[FEAT] Auto train matches

### ISSUE THREAD

**Issue by linost-xx** [skrashevich/double-take#141]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was an option to auto train face matches. So far I've never had any false positives with compreface-gpu so it would remove some manual labor if there was some automation to learning faces.

**Describe the solution you'd like**
A flag to activate auto training.
A minimum match percentage option that allows auto training. For example, you might have a match at 95% but only want to auto train at 99%.

**Additional context**
Before self hosting facial recognition I had a Google Nest subscription, and the nest system had this feature.

**Comment by ptichalouf** [comment]
really nice idea :)
