### ISSUE TITLE
Home Assistant Install

### ISSUE THREAD

**Issue by LordNex** [skrashevich/double-take#150]
I just found this repo after realizing that the jako one hasn't been updated in a year. Can I run this as a Home Assistant add on or do I need to install it on a separate Linux box with docker?  I tried adding this to the add ins store and received and error. Should I take out the old version first? Does this one come bundled with CompreFace or does I need a separate instance of it running. Thanks for the help guys!

**Comment by LordNex** [comment]
Never mind. I found the hass add ons. Thanks for keeping this maintained and up to date. I really rely on this to up my NVR recognition. Would it get any benefit from being on a Jetson Nano? Currently Frigate is running on a separate install of Linux on a 40'core 265gig ram server with a coral TPU passed through to Frigate. I was going to load up CompreFace on the nano but I'm wondering if offloading both out of Home Assistant would improve my response times at all.

**Comment by Mikescotland** [comment]
> Never mind. I found the hass add ons. Thanks for keeping this maintained and up to date. I really rely on this to up my NVR recognition. Would it get any benefit from being on a Jetson Nano? Currently Frigate is running on a separate install of Linux on a 40'core 265gig ram server with a coral TPU passed through to Frigate. I was going to load up CompreFace on the nano but I'm wondering if offloading both out of Home Assistant would improve my response times at all.

Where did you find the addon?

**Comment by LordNex** [comment]
> > Never mind. I found the hass add ons. Thanks for keeping this maintained and up to date. I really rely on this to up my NVR recognition. Would it get any benefit from being on a Jetson Nano? Currently Frigate is running on a separate install of Linux on a 40'core 265gig ram server with a coral TPU passed through to Frigate. I was going to load up CompreFace on the nano but I'm wondering if offloading both out of Home Assistant would improve my response times at all.
> 
> 
> 
> Where did you find the addon? 

[https://github.com/skrashevich/frigate-hass-addons](https://github.com/skrashevich/frigate-hass-addons)

**Comment by LordNex** [comment]
> > > Never mind. I found the hass add ons. Thanks for keeping this maintained and up to date. I really rely on this to up my NVR recognition. Would it get any benefit from being on a Jetson Nano? Currently Frigate is running on a separate install of Linux on a 40'core 265gig ram server with a coral TPU passed through to Frigate. I was going to load up CompreFace on the nano but I'm wondering if offloading both out of Home Assistant would improve my response times at all.
> > 
> > 
> > 
> > Where did you find the addon? 
> 
> [https://github.com/skrashevich/frigate-hass-addons](https://github.com/skrashevich/frigate-hass-addons)
> 

Wait you wanted the HA add on for DT

[https://github.com/skrashevich/hassio-addons](https://github.com/skrashevich/hassio-addons)
