### ISSUE TITLE
[BUG] Error copy jpg files inside .storage during processing image

### ISSUE THREAD

**Issue by sirhideo** [skrashevich/double-take#173]
**Describe the bug**
Error copying jpg files inside .storage during doubletake processing image.
ENOENT: no such file or directory, copyfile './.storage/matches/397fa834-e9b7-4941-9eb2-2ef5ee541b56.jpg' -> './.storage/latest/unknown.jpg'

**Version of Double Take**
`1.13.11.8-SHA7`

**Expected behavior**
success copy latest.jpg to unknown.jpg? i don't know.

** docker-compose.yml
`version: '3.7'

volumes:
  double-take:

services:
  double-take:
    container_name: double-take
    image: skrashevich/double-take:latest
    restart: unless-stopped
    volumes:
      - /opt/doubletake/storage:/.storage
    ports:
      - 3000:3000
`

**Hardware**
 - amd64
 - Ubuntu
 - Browser (if applicable) [e.g. Chrome, Safari]
 - Docker image: e.g. skrashevich/double-take:latest

**Additional context**

**Comment by sirhideo** [comment]
[doubletake_log.txt](https://github.com/skrashevich/double-take/files/13454892/doubletake_log.txt)

log attached.

**Comment by sirhideo** [comment]
What i see is that the random_file_name.jpg doesn't even exist in /opt/doubletake/storage/matches,  in docker view /.storage, so nothing to be copied across directory.

**Comment by skrashevich** [comment]
https://github.com/skrashevich/double-take/issues/159#issuecomment-1826925872

**Comment by sirhideo** [comment]
i have taken a very close look on the logs for every process image.  The copy jpg issue only happens occasionally and so some images show up on Match UI and some were totally ignored.

  I have .storage/latest, .storage/matches and .storage/train directory and mode is 755 (both inside/outside docker).  I have now changed to 777 and see how it goes.
