### ISSUE TITLE
[BUG] Frigate MQTT jpg and frigate/events

### ISSUE THREAD

**Issue by Mikescotland** [skrashevich/double-take#177]
**Describe the bug**
It looks like mqtt topic frigate/events doesn't receive any mqtt jpg's. 
We can change it to frigate/+/person/snapshot and then mqtt properly is processed. However, in this case Double Take doesn't get any mqtt event and doesn't pull any "latest" or "snapshot" from frigate. Also, in this case it does not update any sublabel in frigate.

**Version of Double Take**
`X.X.X-SHA7`

**Expected behavior**
To be able to receive mqtt jpg and also process API frigate snapshot and latest with sublabel update. Maybe subscribe to both topics?

**Screenshots**

**Hardware**
 - Architecture or platform: amd64
 - OS: Ubuntu
 - Browser (if applicable) n.a
 - Docker image (if applicable) HA Addon

**Additional context**

**Comment by skrashevich** [comment]
fixed in latest beta. as a workaround, you can add to config you cameras manually:
```
frigate:
  cameras:
    - your_camera_1
    - your_camera_2
```

**Comment by Mikescotland** [comment]
Sorry for being a pest, but how this workaround is supposed to work? I have one camera passed to DoubleTake, and the issue is with mqtt not working together with snaphots/latest...

**Comment by rossdargan** [comment]
This looks like it's still an issue. Switching back to jakowenko's version and I get detections via MQTT, using your fork I never get a detection from mqtt.

**Comment by Mikescotland** [comment]
Absolutely not an issue.
Take a look at pics 
![Screenshot_20240118_130151](https://github.com/skrashevich/double-take/assets/52081323/b657fac0-596b-4bba-8533-6b829d746fde)
![Screenshot_20240118_130349](https://github.com/skrashevich/double-take/assets/52081323/c5172a99-9581-4426-a574-bbaedef501e8)

**Comment by rossdargan** [comment]
what build are you using? It just absolutely refused to work on latest for me, but switching to jakowenko's version and it works perfectly.
