### ISSUE TITLE
[BUG] Notification condition stopping sending notification

### ISSUE THREAD

**Issue by Mikescotland** [skrashevich/double-take#179]
Sergey
Could you shed some light and explain what this condition in the notification automation does:

condition: template
value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'

I was manually testing on my pics and first notification has been sent, however subsequent were blocked in HA:
![Clipboard47](https://github.com/skrashevich/double-take/assets/52081323/153b87b9-4d22-4ed7-831d-87cd9491b37f)

Thank you

**Comment by skrashevich** [comment]
This condition is necessary so that notifications don't duplicate.

**Comment by Mikescotland** [comment]
For some kind of reasons, after some time (minutes, maybe 10 or something), this automation throws completely empty notification, or even two. 
Is there any mqtt message just saying X has been detected? It is super hard to make any automation based on this entity.
