### ISSUE TITLE
[FEAT] Decrease processing time

### ISSUE THREAD

**Issue by Mikescotland** [skrashevich/double-take#180]
**Is your feature request related to a problem? Please describe.**
Decrease time to communicate with CompraFace
This has been described here:
https://github.com/jakowenko/double-take/issues/280
Esentially, takes 1-3 seconds to recognise in DoubleTake vs 500 ms just to use CompreFace API directly

**Describe the solution you'd like**

**Additional context**
Sergey, mind to look  into it? Thank you

**Comment by skrashevich** [comment]
Do you have this problem reproduced at my latest release? You refer to a one-year-old issue
Test with settings:
```
stop_on_match: true
opencv_face_required: false
det_prob_threshold: 0.8
```

**Comment by Mikescotland** [comment]
Thanks. Decreased to 0.7 s.
