### ISSUE TITLE
[FEAT] Use Super Resolution module in CodeProject AI Server

### ISSUE THREAD

**Issue by jakabo27** [skrashevich/double-take#291]
Is it possible to use the Super Resolution module in CodeProject.AI Server? I successfully installed it on the server, but I don't know how to change the image+command passed by Double Take to tell it to run SuperResolution on the image before running Face Recognition.  

**Solution I'd like**
In the YAML config for aiserver detector have a flag for "additional image processing" or similar, where we can turn on other filters (mainly Super Resolution). 

![image](https://github.com/skrashevich/double-take/assets/29758597/a1a1eca4-7db3-480b-85cd-5f06a0ec2ef3)

![image](https://github.com/skrashevich/double-take/assets/29758597/3d92d057-eb78-4396-ba6c-e446b8a21ba7)

**Comment by jsapede** [comment]
Could be great to have chain analysis paramétrisation like sending to codeproject to enhance résolution then to compreface
