### ISSUE TITLE
[BUG] Missing Person Sensors in HA

### ISSUE THREAD

**Issue by weswitt** [skrashevich/double-take#430]
I am running v1.13.11.8 double-take with the latest compreface, frigate & HA. Double-take recognizes the faces, gets a match just fine but the person sensor for the detected face is never created in HA. I only see the sensor for the camera (sensor.double_take_easthouseside). Is there a way to get the sensors created? I know that they're supposed to be created automatically but that is not happening.

![image](https://github.com/skrashevich/double-take/assets/15125944/e12fc569-46bb-4ff8-a936-8d2456589ad0)

**Comment by csib** [comment]
I've got the same problem, did not find yet any solution

**Comment by danielbn21** [comment]
I too have the same issue. The only sensor that is created is the unknown sensor but none of the other person sensor are created. 

here is the error that I'm getting 

> error: TypeError: MQTT: recognize error: Cannot read properties of undefined (reading 'DEVICE_TRACKER_TIMEOUT')
    at /double-take/api/src/util/mqtt.util.js:278:32
    at Array.forEach (<anonymous>)
    at module.exports.recognize (/double-take/api/src/util/mqtt.util.js:239:13)
    at module.exports.start (/double-take/api/src/controllers/recognize.controller.js:184:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Devstored** [comment]
I have the same problem. Did you find a solution?
