### ISSUE TITLE
[BUG] Can't run on port 1883

### ISSUE THREAD

**Issue by ptichalouf** [skrashevich/double-take#47]
i dunno why i can't use the default port 1883 on MQTT only 8883 is ok i don't want to change all my other stuff everything is on 1883. how can i make your fork work on 1883 ? thanks for your work and time :)

**Comment by skrashevich** [comment]
Please, show your config (mqtt part). Don't forget to remove password :)

**Comment by ptichalouf** [comment]
Thanks for taking some time to help me but with this config with your fork 

`mqtt:
  # Required: host name
  host: 192.168.1.5
  # Optional: port (default: shown below)
  port: 1883
  topics:
    # mqtt topic for frigate message subscription
    frigate: frigate/events
    #  mqtt topic for home assistant discovery subscription
    homeassistant: homeassistant
    # mqtt topic where matches are published by name
    matches: double-take/matches
    # mqtt topic where matches are published by camera name
    cameras: double-take/cameras`

i have this error : 


`info: Double Take v1.13.3
error: MQTT: connect ECONNREFUSED 192.168.1.5:8883
error: MQTT: offline
warn: MQTT: reconnecting
error: MQTT: connect ECONNREFUSED 192.168.1.5:8883`

**Comment by skrashevich** [comment]
Found a problem. I'll prepare a fix now

**Comment by skrashevich** [comment]
fixed in latest build
