### ISSUE TITLE
[BUG] How Switch from olf repo to yours

### ISSUE THREAD

**Issue by ptichalouf** [skrashevich/double-take#493]
hello  i have the home assistant addon but the regular repo isn't updated. Someone know how can i switch to this one ? https://github.com/skrashevich/double-take

of maybe making your own addon ?

**Comment by d-allin** [comment]
Remove your current installation.
Follow the instructions in the link that you've already found to add the addon, then install it.
You have to click one button and it's done for you, or:

> navigate to Configuration > Add-ons, Backups & Supervisor > Add-on Store > ... > Repositories and add https://github.com/skrashevich/hassio-addons to the list.

**Comment by elektrinis** [comment]
This works, thank you.
However MQTT does not connect with same confit as older addon....
error: MQTT: getaddrinfo ENOTFOUND core-mosquitto:1883

**Comment by d-allin** [comment]
If MQTT is running on your home assistant installation, you'll need to change `host` in your double-take config to match the ip address of your home assistant instance rather than localhost.

Suggest you close the issue or at least change the label as you are not experiencing any bugs. There is a Discussions section on the project that is more suitable for configuration talks.

**Comment by mattbruman** [comment]
> If MQTT is running on your home assistant installation, you'll need to change `host` in your double-take config to match the ip address of your home assistant instance rather than localhost.
> 
> Suggest you close the issue or at least change the label as you are not experiencing any bugs. There is a Discussions section on the project that is more suitable for configuration talks.

I am getting the same thing with this version of double take. 

`24-06-11 13:30:28 warn: MQTT: reconnecting
24-06-11 13:30:28 error: MQTT: getaddrinfo ENOTFOUND 192.168.1.10:1883`

Other versions work fine with the same config.

**Comment by d-allin** [comment]
> > If MQTT is running on your home assistant installation, you'll need to change `host` in your double-take config to match the ip address of your home assistant instance rather than localhost.
> > Suggest you close the issue or at least change the label as you are not experiencing any bugs. There is a Discussions section on the project that is more suitable for configuration talks.
> 
> I am getting the same thing with this version of double take.
> 
> `24-06-11 13:30:28 warn: MQTT: reconnecting 24-06-11 13:30:28 error: MQTT: getaddrinfo ENOTFOUND 192.168.1.10:1883`
> 
> Other versions work fine with the same config.

This should be reported as a seperate issue if you think it's a bug. (Actually, the issue at the top of the list [#515] covers this.)

Are you migrating from the unmaintained version?

If you're putting the port in the `host` parameter, remove it. Use the separate `port` parameter or don't declare it to use the defaults (1883 if `protocol` is mqtt or 8883 if `protocol` is mqtts).

For example:

```
mqtt:
  host: 192.168.1.10
  user: mqtt-user
  password: !secret mqtt_password
  client_id: double-take
  protocol: mqtt # mqtts enables TLS
  port: 1883 # defaults to 8883 if protocol is set to mqtts
```
