### ISSUE TITLE
New release using codeproject 

### ISSUE THREAD

**Issue by bigmack48** [skrashevich/double-take#51]
How do I get your new release on home assistant using codeproject ai. I getting errors using current version.

23-05-14 17:59:09 info: processing frontyard: 8de6b3c8-410e-44be-9a23-5a0e7b3a476c
23-05-14 17:59:09 info: processing frontyard: 1684101483.656355-l1wiog
23-05-14 17:59:09 error: TypeError: aiserver process error: Cannot read properties of undefined (reading 'recognize')
    at module.exports.recognize (/double-take/api/src/util/detectors/actions/index.js:4:24)
    at Object.module.exports.process (/double-take/api/src/util/process.util.js:160:28)
    at Object.module.exports.start (/double-take/api/src/util/process.util.js:137:28)
    at module.exports.polling (/double-take/api/src/util/process.util.js:55:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async module.exports.start (/double-take/api/src/controllers/recognize.controller.js:152:7)
23-05-14 17:59:09 info: done processing frontyard: 8de6b3c8-410e-44be-9a23-5a0e7b3a476c in 0.01 sec
23-05-14 17:59:09 info: {
  id: '8de6b3c8-410e-44be-9a23-5a0e7b3a476c',
  duration: 0.01,
  timestamp: '2023-05-14T21:59:09.769Z',
  attempts: 1,
  camera: 'frontyard',
  zones: [],
  counts: { person: 0, match: 0, miss: 0, unknown: 0 },
  matches: [],
  misses: [],
  unknowns: []

**Comment by skrashevich** [comment]
you can use repository `https://github.com/skrashevich/hassio-addons` to install hassio add-on of this fork

**Comment by bigmack48** [comment]
Thank you for fixing this problem. So far is working.Have a good day.GregSent from my iPhoneOn Jun 2, 2023, at 12:40 AM, Sergey Krashevich ***@***.***> wrote:﻿
you can use repository https://github.com/skrashevich/hassio-addons to install hassio add-on of this fork

**Comment by bigmack48** [comment]
I just got one question. I now getting an error in log file after few days after I got it work.The double take log states that recognizer.log file is missing out the double take directory.Now I not able to connect to codeproject ai.Do you want me to add this to issues log?Thank you for you help.Greg MackSent from my iPhoneOn Jun 2, 2023, at 2:09 PM, Gregory Mack ***@***.***> wrote:﻿
Thank you for fixing this problem. So far is working.Have a good day.GregSent from my iPhoneOn Jun 2, 2023, at 12:40 AM, Sergey Krashevich ***@***.***> wrote:﻿
you can use repository https://github.com/skrashevich/hassio-addons to install hassio add-on of this fork

**Comment by skrashevich** [comment]
Please, don't use "betadebug" image in production. This image only for testing purposes (including my internal tests of new features).
Just use "beta" or "latest" label instead of "betadebug" and this error will go away

**Comment by skrashevich** [comment]
fixed in v1.13.8.1

**Comment by skrashevich** [comment]
try again now. you was faster then dockerhub :)

**Comment by bigmack48** [comment]
Hi,I was able to update to your new version: V1.13.9.Now I getting timeout error and codeproject indicator is not green.I am able to train a face, but it taking longer time than before. Do you have any idea why this is happening.info: Double Take v1.13.9
info: MQTT: connected
info: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
info: gwen mack: queuing 1 file(s) for training
info: gwen mack: training complete in 18.48 sec
error: AxiosError: timeout of 15000ms exceededI see you have a plug-in for codeproject ai.Is that available for me to test now.Any help will be appreciated.Thank you GregSent from my iPhoneOn Jun 8, 2023, at 9:07 AM, Gregory Mack ***@***.***> wrote:﻿Same error: manifest unknownFailed to install add-onSent from my iPhoneOn Jun 8, 2023, at 8:42 AM, Sergey Krashevich ***@***.***> wrote:﻿
try again now. you was faster then dockerhub :)

**Comment by skrashevich** [comment]
Do you use ai.server on raspberry Pi?

**Comment by bigmack48** [comment]
My codeproject Ai server is running on window 11 machine. With a fast cpu.  I7.Sent from my iPhoneOn Jun 8, 2023, at 12:49 PM, Sergey Krashevich ***@***.***> wrote:﻿
show your config, please.
don't forgot to hide passwords before publish!

**Comment by skrashevich** [comment]
Я имел в виду конфигурационный файл double-take :)

**Comment by bigmack48** [comment]
What version of frigate are using. There are. Multiple version out there. I use beta version which is not full version.If you need any additional info. Please email me.Sent from my iPhoneOn Jun 8, 2023, at 3:15 PM, Sergey Krashevich ***@***.***> wrote:﻿
Я имел в виду конфигурационный файл double-take :)

**Comment by bigmack48** [comment]
Thanks you for fixing the program.I need a few more days to look over things to make sure everything is working correctly. I will let you know if I have any additional problems.Thanks, you have been big help.GregSent from my iPhoneOn Jun 8, 2023, at 3:43 PM, Gregory Mack ***@***.***> wrote:﻿What version of frigate are using. There are. Multiple version out there. I use beta version which is not full version.If you need any additional info. Please email me.Sent from my iPhoneOn Jun 8, 2023, at 3:15 PM, Sergey Krashevich ***@***.***> wrote:﻿
Я имел в виду конфигурационный файл double-take :)
