### ISSUE TITLE
[BUG] Xfering from old repo works well with tiny fix

### ISSUE THREAD

**Issue by jds11111** [skrashevich/double-take#515]
**Describe the bug**
I was using the unmaintained repo and wanted to transfer to this one. I kept my docker-compose file the same, except switching images. I also kept the old config file the same. Double take started fine (green dot), as well as frigate and compre-face. The exception was MQTT. The log file from DT said that MQTT broker was down. After a little experimentation, I found that removing the port from the IP address of the broker fixed it. Do what you want with this information, but thought that it might help some people. 

Thanks for forking and updating!

**Comment by elektrinis** [comment]
I had this, and it did not work: host: core-mosquitto:1883
Removed port, and get error connection refused: not authorized.
