### ISSUE TITLE
Notify Telegram

### ISSUE THREAD

**Issue by SergeySergeevitch** [skrashevich/double-take#52]
How to properly set up a notification?

![image](https://github.com/skrashevich/double-take/assets/74430515/5403af81-3ef2-46c7-8d05-ebb36d0ce989)

**Comment by Xender0** [comment]
Please refer to this documentation

https://core.telegram.org/tdlib/notification-api/

**Comment by SergeySergeevitch** [comment]
Understood. Sends notification only to trained individuals. Can I add settings - one notification per face per day? )

**Comment by Xender0** [comment]
i guess u can use loop for it

**Comment by skrashevich** [comment]
> Understood. Sends notification only to trained individuals. Can I add settings - one notification per face per day? )

At present, it's not realised. And it's really unusual request. What task are you attempting to solve with it?

На текущий момент такой возможности нет. Довольно необычный запрос. Какую задачу вы пытаетесь с помощью этого решить?

**Comment by SergeySergeevitch** [comment]
See what time each employee arrives. An employee came - a notification came. The next employee came - a notification came. Repeat the next day.

**Comment by skrashevich** [comment]
Understood. Unfortunately, the current architecture of the project doesn't  allow for such a feature to be implemented without significant changes. As an alternative, I could develop the ability to send a daily summary at a specified time of the recognized faces.
