### ISSUE TITLE
[FEAT] ai server license plate recognition?

### ISSUE THREAD

**Issue by JonGilmore** [skrashevich/double-take#54]
**Is your feature request related to a problem? Please describe.**
I have recently started testing CodeProject.ai Server for face recognition with double-take and noticed that is supports LPR. Any chance double-take would support this in the future as well? 

**Describe the solution you'd like**
Support added for LPR 

**Additional context**

<img width="739" alt="image" src="https://github.com/skrashevich/double-take/assets/7232986/6705c82f-f939-4a12-8c30-7f011ea84fc6">

**Comment by DrSpaldo** [comment]
I would also be interested in this one

**Comment by SamanthaJT-dev** [comment]
Any updates?

**Comment by JonGilmore** [comment]
Remove stale label

**Comment by rhamblen** [comment]
OK I was looking at https://github.com/robmarkcole/HASS-plate-recognizer
which uses https://platerecognizer.com/
what would be good is to just call the platerecognizer api and send the image to it and get the info back.
If robbarkcole has done the heavy lifting of the use of the API when you send the image, then you could take advantage of this to just take the frigate notification and send if over to platerecogniser.  

Thoughts???

**Comment by DrSpaldo** [comment]
I've been using this one in the meantime and it is pretty reliable:
