### ISSUE TITLE
[BUG] timezone /  logs

### ISSUE THREAD

**Issue by jsapede** [skrashevich/double-take#545]
**Describe the bug**
Cant get timezone to match in logs
changed many times the settings in config file but time in logs doesnt change, there are always 2h difference.

**Version of Double Take**
1.13.12.0.rc3

**Expected behavior**
have consistency in time between matches and logs 

**Screenshots**
![image](https://github.com/skrashevich/double-take/assets/66303110/93ff0b7c-a490-4dae-bc74-d2cf9696d76a)

![image](https://github.com/skrashevich/double-take/assets/66303110/b7e9eaa7-dbaa-4176-a671-01b96bc53943)

![image](https://github.com/skrashevich/double-take/assets/66303110/d2ded9f6-4d63-4139-8477-757e4765b2a1)

**Hardware**
 - Architecture or platform: amd64 / proxmox
 - OS: debian / docker / portainer
 - Docker image skrashevich/double-take:1.13.12.0.rc3

**Configuration**
```

time:
  timezone: Europe/Paris
```

**Additional context**
tried with timezone : CET, and no changes also 
had similar problem with standard release.

**Comment by ammgws** [comment]
Try adding the `TZ` env var to your docker compose file:
![image](https://github.com/skrashevich/double-take/assets/20397027/dc534c71-64eb-4102-a51f-28812e3642ea)

**Comment by jsapede** [comment]
thanks, seems to work ! 
i'm quite sure i've tried this before !
