### ISSUE TITLE
[BUG] i cant get it started I get adres already in use but its not.

### ISSUE THREAD

**Issue by pbvdven** [skrashevich/double-take#58]
I cant get the container started i get error Error: listen EADDRINUSE: address already in use :::3000? 

**config**

mqtt:
  host: 192.168.2.16:1883
  username: dtake
  password: 
  topics:
    # mqtt topic for frigate message subscription
    frigate: frigate/events
    #  mqtt topic for home assistant discovery subscription
    homeassistant: homeassistant
    # mqtt topic where matches are published by name
    matches: double-take/matches
    # mqtt topic where matches are published by camera name
    cameras: double-take/cameras
    
frigate:
  url: http://192.168.2.144:5000
  update_sub_labels: true
  cameras:
    - voordeur
  labels:
    - person

detectors:
  compreface:
    url: http://192.168.2.16:8452
    # recognition api key
    key: 
    # number of seconds before the request times out and is aborted
    timeout: 180
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    
cameras:
  voordeur:
    detect:
      match:
        # save match images
        save: true
        # include base64 encoded string in api results and mqtt messages
        # options: true, false, box
        base64: false
        # minimum confidence needed to consider a result a match
        confidence: 90
        # hours to keep match images until they are deleted
        purge: 168
        # minimum area in pixels to consider a result a match 10000
        min_area: 6000
      unknown:
        # save unknown images
        save: true
        # include base64 encoded string in api results and mqtt messages
        # options: true, false, box
        base64: false
        # minimum confidence needed before classifying a name as unknown
        confidence: 40
        # hours to keep unknown images until they are deleted
        purge: 8
        # minimum area in pixels to keep an unknown result
        min_area: 0

**compose:**
version: '3.7'

volumes:
  double-take:

services:
  double-take:
    container_name: double-take
    image: skrashevich/double-take:latest
    #jakowenko/double-take
    restart: unless-stopped
    volumes:
      - /usr/share/hassio/homeassistant/double-take:/.storage
    ports:
      - 3580:3000
**Log error:**
info: Double Take v1.13.9
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at Object.module.exports.start (/double-take/api/server.js:23:52)
Emitted 'error' event on Server instance at:
    at Server.incomingRequest (/double-take/api/node_modules/@opentelemetry/instrumentation-http/build/src/http.js:280:33)
    at emitErrorNT (node:net:1490:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
**Additional context**

**Comment by juan11perez** [comment]
I can report the same issue

**Comment by meks007** [comment]
switch to 1.13.9 and dont use latest

**Comment by skrashevich** [comment]
Fixed in the last latest build.
