### ISSUE TITLE
[BUG] MQTT connection not possible on other port

### ISSUE THREAD

**Issue by bagsik** [skrashevich/double-take#60]
**Describe the bug**
Connection to MQTT server not possible if not on default port

**Version of Double Take**
since https://github.com/skrashevich/double-take/commit/c94d769c24460896c0a0807eff3f4f259ad6828e

**Expected behavior**
with the refactoring of the mqtt connection it isn't possible to connect to server, when the port isn't default

**Comment by linkwellfook** [comment]
I'm seeing this, however I'm using default 1883.
Mosquitto addon installed and working
Using username and password as defined in mosquitto
It was working in v1.13.1 but broke in v1.13.9 and v1.13.10 
portion of the logs
23-06-28 10:50:30 error: MQTT: getaddrinfo ENOTFOUND homeassistant_ip_address:1883
23-06-28 10:50:40 warn: MQTT: reconnecting
23-06-28 10:50:40 error: MQTT: getaddrinfo ENOTFOUND 192.168.1.56:1883
23-06-28 10:50:50 warn: MQTT: reconnecting
23-06-28 10:50:50 error: MQTT: getaddrinfo ENOTFOUND 192.168.1.56:1883

**Comment by bagsik** [comment]
@linkwellfook 
in the config you have to use only the hostname/ip, now it's not possible to add the port. so if you use default port, it works fine

**Comment by linkwellfook** [comment]
hi,
tx.  Working now

**Comment by skrashevich** [comment]
fixed in #62 (thx @bagsik ), will be merged into next release after some tests
