### ISSUE TITLE
[BUG] Missing Person Sensors in HA

### ISSUE THREAD

**Issue by Devstored** [skrashevich/double-take#606]
**Describe the bug**
I am running v1.13.11.8 double-take with the latest compreface, frigate & HA. Double-take recognizes the faces, gets a match just fine but the person sensor for the detected face is never created in HA. I only see the sensor for the camera (sensor.double_take_easthouseside). Is there a way to get the sensors created? I know that they're supposed to be created automatically but that is not happening.
![image](https://github.com/user-attachments/assets/064d7564-416b-4b0e-ac06-118ede88a854)

**Version of Double Take**
`v1.13.11.8`

I reopened the ticket: https://github.com/skrashevich/double-take/issues/430

**Comment by bachoo786** [comment]
any update on this I have the same issue?
