### ISSUE TITLE
[BUG] Time Issue - Out By 1 Hour

### ISSUE THREAD

**Issue by townsmcp** [skrashevich/double-take#61]
**Describe the bug**
I am in the UK, and currently we have the time set to summer time (GMT+1).
I have DT as an add-on in Home Assistant.
Home Assistant is set to the correct time zone (HA entities are reporting the correct time when I look).
Frigate is running in a docker container in an LXC on Proxmox and I have TZ set for Frigate to 'Europe/London'.
Home Assistant is running in the same Proxmox but in a VM.
The issue I am encountering is time in DT is out by an hour - is there a configurable option to bring this inline correctly for the HA addon install?

**Version of Double Take**
1.13.9

**Expected behavior**
When an event occurs, the recorded date/time is the correct date/time

**Screenshots**
Frigate event:
<img width="401" alt="image" src="https://github.com/skrashevich/double-take/assets/14061617/aac34e31-8606-4cd5-84f5-baae96a16aba">
Same event from DT:
<img width="663" alt="image" src="https://github.com/skrashevich/double-take/assets/14061617/5574f8ab-4d4c-44ad-8c66-70795335598f">
Notice the 'CreatedAt' time in DT states 12:26 but the event time recorded in Frigate states 13:23 (I can handle the 3 minute issue)
```
{
  "detector": "compreface",
  "duration": 0.59,
  "name": "unknown",
  "confidence": 52.82,
  "match": false,
  "box": {
    "top": 33,
    "left": 211,
    "width": 48,
    "height": 48
  },
  "checks": [
    "confidence too low: 52.82 < 85"
  ],
  "createdAt": "2023-06-27T12:26:44.190Z",
  "updatedAt": null
}
```

**Comment by skrashevich** [comment]
https://github.com/skrashevich/double-take#time

**Comment by townsmcp** [comment]
@skrashevich 
Thank you. I hadn't seen that when searching for time :(
I changed the value to GMT, save and restarted DT - no change, still one hour behind (to be expected I guess as it would be GMT+1)
I then changed the value to BST, save and restarted DT - also no change, still one hour behind.
Any other suggestions?

**Comment by skrashevich** [comment]
Are you using add-on from the repository https://github.com/skrashevich/hassio-addons ?

**Comment by townsmcp** [comment]
Yes, it shows up as 'svk's Hass.io Add-ons':
<img width="409" alt="image" src="https://github.com/skrashevich/double-take/assets/14061617/0a82fac9-5346-43d1-be75-bed5bcf43a86">
<img width="508" alt="image" src="https://github.com/skrashevich/double-take/assets/14061617/8b2b18ac-8f98-4888-bc6b-0bfdb44d80a6">

**Comment by skrashevich** [comment]
you can try v1.13.10

**Comment by townsmcp** [comment]
> you can try v1.13.10

Thank you. That installed and is working perfectly. I left the code set to the following:
```
time:
  # defaults to iso 8601 format with support for token-based formatting
  # https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens
  format:
  # time zone used in logs
  timezone: Europe/London
```
