### ISSUE TITLE
Snapshots cropping issue

### ISSUE THREAD

**Issue by mikhail-ucesys** [skrashevich/double-take#63]
I apologize if I am not reporting the issue properly. I recently started using Frigate, DoubleTake, and Compreface with a single camera Hikvision DS-2CD2387G2. I am not sure where the issue is. I am getting low resolution event images on DoubleTake for snapshots and mqtt. The “latest” images seem to have consistently high resolution. Snapshot seems to be always cropped to a person height while “latest” shows the entire area. The snapshot images also pixelated probably because of they have been resized. I tried disabling “snapshot” on Frigate but it did not change anything. Crop is set to False. Image files in frigate/media/clips are all of consistent size - about 2MB for *.jpg and 20MB for *clean.png.

**Version of Double Take**
1.13.10 and 1.13.9

**Expected behavior**
I would expect to see images with the resolution as they have been produced by the camera.

**Hardware**
 - Frigate, DoubleTake, and Compreface are all running in Docker/Ubuntu as a Proxmox VM.

**Comment by skrashevich** [comment]
Please, show double-take configuration file contents. Don't forget to hide passwords!

P.S. If you are russian-speaking, you can go to telegram chat https://t.me/FrigateNVR for faster support

**Comment by mikhail-ucesys** [comment]
Hi, here is the double-take config:
`
auth: true

mqtt:
  host: ...
  username: mqtt
  password: ...
  topics:
    frigate: frigate/events
    homeassistant: homeassistant
    matches: double-take/matches
    cameras: double-take/cameras
    
frigate:
  url: ...
  update_sub_labels: true

  stop_on_match: true

  min_area: 2000

  labels:
    - person

  attempts:
    latest: 50
    snapshot: 50
    mqtt: true
    delay: 0

  image:
    height: 2160
    
detectors:
  compreface:
    url: ...
    key: ...
    timeout: 15
    det_prob_threshold: 0.8
    opencv_face_required: false
    
detect:
  match:
    save: true
    base64: false
    confidence: 80
    purge: 168
    min_area: 10000

  unknown:
    save: true
    base64: false
    confidence: 40
    purge: 168
    min_area: 0


`

**Comment by mikhail-ucesys** [comment]
Attached is the config for double-take:

[double-take.txt](https://github.com/skrashevich/double-take/files/11939949/double-take.txt)

**Comment by skrashevich** [comment]
Looks like, it's a frigate misconfiguration. I don't see any problems in provided config 
Check in your's **frigate** config:
```
cameras:
  <cameraname>:
    mqtt:
        crop: False # <- don't crop snapshots in mqtt
        height: 2160 # <- really too much, but get this value from your DT config
        quality: 80 # <- at least
```

**Comment by skrashevich** [comment]
@mikhail-ucesys  is problem solved?

**Comment by mikhail-ucesys** [comment]
I tried with crop Off and On in mqtt and it did not change anything. I will try to get help in the telegram. 
Thank you!
