### ISSUE TITLE
[FEAT] Enable/Disable face detection via MQTT / HA Addon

### ISSUE THREAD

**Issue by AndLindemann** [skrashevich/double-take#64]
**Is your feature request related to a problem? Please describe.**
I'm using AWS Recognition as it gives much better results for me than CompreFace (lots of false positives there even with good training images). That of course generates some cost when I submit images for face detection.

**Describe the solution you'd like**
It'd help reduce costs if I could dynamically enable/disable the face detection from Home Assistant, either by publishing to MQTT or by using an MQTT-based switch in HA.
That way I could use HA to only enable face detection when I actually need it, for example if someone just came home, which is currently my only use case. This way I could avoid detecting faces when everyone is already home and someone just comes up to my door or if no-one is home of course.
Would it be feasible to add an MQTT topic where we could post to enable/disable face detection in double take either completely, or based on recognition service / camera? For me it'd be good enough if I could just have a simple on/off toggle to disable or enable it completely.

**Comment by skrashevich** [comment]
Maybe in the described case it's more logical to implement the ability to disable detectors rather than cameras?

**Comment by AndLindemann** [comment]
Yes, disabling detectors would work just fine for this.

**Comment by joeblack2k** [comment]
Is there an update to this?

**Comment by pelayolartategui** [comment]
Maybe this could be achieved using the API? Is any way to achieve it changing the config?

**Comment by skrashevich** [comment]
As a temporary solution, added the detector enable setting to the configuration: https://github.com/skrashevich/double-take/pull/194/commits/d76d6a62dc808d7cd2cd276e00a693c4628ae26d
