### ISSUE TITLE
[BUG] Crash in logs

### ISSUE THREAD

**Issue by Nonobis** [skrashevich/double-take#75]
**Describe the bug**
Big crash on log on main.go ...

**Version of Double Take**
v1.3.10

**Expected behavior**

**Screenshots**

**Hardware**
 - OS: Docker
 - Browser (if applicable) Brave

**Additional context**

2023/07/08 14:48:46 daemon started
SIGILL: illegal instruction
PC=0x94bb11 m=3 sigcode=2
signal arrived during cgo execution
instruction bytes: 0xc5 0xf9 0xef 0xc0 0x48 0x89 0xe5 0x41 0x57 0x41 0x56 0x41 0x55 0x41 0x54 0x53

goroutine 5 [syscall]:
runtime.cgocall(0x8b51c0, 0xc000057d78)
	runtime/cgocall.go:157 +0x5c fp=0xc000057d50 sp=0xc000057d18 pc=0x40c4bc
github.com/Kagami/go-face._Cfunc_facerec_init(0x2130350)
	_cgo_gotypes.go:203 +0x49 fp=0xc000057d78 sp=0xc000057d50 pc=0x6a9fc9
github.com/Kagami/go-face.NewRecognizer({0x7ffd02ae3ece?, 0xd15740?})
	github.com/Kagami/go-face@v0.0.0-20210630145111-0c14797b4d0e/face.go:68 +0x67 fp=0xc000057de0 sp=0xc000057d78 pc=0x6aa467
github.com/leandroveronezi/go-recognizer.(*Recognizer).Init(0xc000180060, {0x7ffd02ae3ece, 0x16})
	github.com/leandroveronezi/go-recognizer@v1.0.1/recognizer.go:50 +0x7e fp=0xc000057e08 sp=0xc000057de0 pc=0x6ca81e
main.worker()
	github.com/skrashevich/double-take/recognizer/main.go:172 +0xb5 fp=0xc000057fc0 sp=0xc000057e08 pc=0x8b2495
main.looper()
	github.com/skrashevich/double-take/recognizer/main.go:154 +0x19 fp=0xc000057fe0 sp=0xc000057fc0 pc=0x8b2399
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000057fe8 sp=0xc000057fe0 pc=0x46f561
created by main.main
	github.com/skrashevich/double-take/recognizer/main.go:137 +0x991

goroutine 1 [runnable]:
runtime.gopark(0xc0000700c0?, 0xc000070120?, 0xeb?, 0xe9?, 0xc0000f5ac8?)
	runtime/proc.go:381 +0xd6 fp=0xc0000f5a58 sp=0xc0000f5a38 pc=0x43fd16
runtime.chansend(0xc0001840c0, 0xc0000f5b58, 0x1, 0x4760c6?)
	runtime/chan.go:259 +0x42e fp=0xc0000f5ae0 sp=0xc0000f5a58 pc=0x40e46e
runtime.chansend1(0x47601c?, 0x1486dbae728?)
	runtime/chan.go:145 +0x1d fp=0xc0000f5b10 sp=0xc0000f5ae0 pc=0x40e01d
runtime.sigenable(0x1)
	runtime/signal_unix.go:202 +0x65 fp=0xc0000f5b58 sp=0xc0000f5b10 pc=0x4520a5
os/signal.signal_enable(0xe86cdd64?)
	runtime/sigqueue.go:223 +0x73 fp=0xc0000f5b78 sp=0xc0000f5b58 pc=0x46bfd3
os/signal.enableSignal(...)
	os/signal/signal_unix.go:49
os/signal.Notify.func1(0xcdda80?)
	os/signal/signal.go:145 +0x73 fp=0xc0000f5ba0 sp=0xc0000f5b78 pc=0x6cbcd3
os/signal.Notify(0xc000070060, {0xc000180000, 0x3, 0xc0000f5d00?})
	os/signal/signal.go:165 +0x196 fp=0xc0000f5c18 sp=0xc0000f5ba0 pc=0x6cbb56
github.com/sevlyar/go-daemon.ServeSignals()
	github.com/sevlyar/go-daemon@v0.1.6/signal.go:33 +0x1af fp=0xc0000f5d40 sp=0xc0000f5c18 pc=0x6ce62f
main.main()
	github.com/skrashevich/double-take/recognizer/main.go:139 +0x996 fp=0xc0000f5f80 sp=0xc0000f5d40 pc=0x8b2236
runtime.main()
	runtime/proc.go:250 +0x207 fp=0xc0000f5fe0 sp=0xc0000f5f80 pc=0x43f8e7
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000f5fe8 sp=0xc0000f5fe0 pc=0x46f561

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000044fb0 sp=0xc000044f90 pc=0x43fd16
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.forcegchelper()
	runtime/proc.go:305 +0xb0 fp=0xc000044fe0 sp=0xc000044fb0 pc=0x43fb50
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x46f561
created by runtime.init.6
	runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000045780 sp=0xc000045760 pc=0x43fd16
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:278 +0x8e fp=0xc0000457c8 sp=0xc000045780 pc=0x42c02e
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc0000457e0 sp=0xc0000457c8 pc=0x4214e6
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x46f561
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00006c000?, 0xdfa260?, 0x1?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000045f70 sp=0xc000045f50 pc=0x43fd16
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.(*scavengerState).park(0x127c560)
	runtime/mgcscavenge.go:400 +0x53 fp=0xc000045fa0 sp=0xc000045f70 pc=0x429f53
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:628 +0x45 fp=0xc000045fc8 sp=0xc000045fa0 pc=0x42a525
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x421486
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x46f561
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x127ce20?, 0xe0?, 0x24?, 0xc000044770?)
	runtime/proc.go:381 +0xd6 fp=0xc000044628 sp=0xc000044608 pc=0x43fd16
runtime.runfinq()
	runtime/mfinal.go:193 +0x107 fp=0xc0000447e0 sp=0xc000044628 pc=0x420527
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x46f561
created by runtime.createfing
	runtime/mfinal.go:163 +0x45

goroutine 6 [chan send, locked to thread]:
runtime.gopark(0x1?, 0x2?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc000046ea0 sp=0xc000046e80 pc=0x43fd16
runtime.chansend(0xc000184000, 0xc000046f8f, 0x1, 0x2?)
	runtime/chan.go:259 +0x42e fp=0xc000046f28 sp=0xc000046ea0 pc=0x40e46e
runtime.chansend1(0xc000000002?, 0xc000046f98?)
	runtime/chan.go:145 +0x1d fp=0xc000046f58 sp=0xc000046f28 pc=0x40e01d
runtime.ensureSigM.func1()
	runtime/signal_unix.go:1015 +0x15a fp=0xc000046fe0 sp=0xc000046f58 pc=0x46793a
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x46f561
created by runtime.ensureSigM
	runtime/signal_unix.go:987 +0xbd

goroutine 7 [syscall]:
runtime.notetsleepg(0x0?, 0x0?)
	runtime/lock_futex.go:236 +0x34 fp=0xc0000477a0 sp=0xc000047768 pc=0x414614
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x2f fp=0xc0000477c0 sp=0xc0000477a0 pc=0x46be0f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19 fp=0xc0000477e0 sp=0xc0000477c0 pc=0x6cc499
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000477e8 sp=0xc0000477e0 pc=0x46f561
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

rax    0x7f4838000b50
rbx    0x7f4838000b20
rcx    0x7f4838000020
rdx    0x7f4838000b50
rdi    0x7f4838000b50
rsi    0x2130350
rbp    0x7f4838000b50
rsp    0x7f484604a810
r8     0x3
r9     0x6e
r10    0x0
r11    0x7f48380008d0
r12    0x2130350
r13    0xa
r14    0xc0000076c0
r15    0x100
rip    0x94bb11
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0
2023/07/08 17:30:34 - - - - - - - - - - - - - - -

**Comment by skrashevich** [comment]
Please, don't use "debug" tag

**Comment by Nonobis** [comment]
debug tag ?

i am on lastest tag from dockerhub ...

**Comment by skrashevich** [comment]
oh, my apologies. because of a stupid type, "debug" builds with some untested code (planned for future versions) leaks into "latest" tag 😞

**Comment by Nonobis** [comment]
will try it tonight thanks :)

**Comment by skrashevich** [comment]
I'm waiting for the results. If the problem is solved, please close this issue

**Comment by Nonobis** [comment]
Solved :) Thanks ^_^
