### ISSUE TITLE
[BUG] Unable to run the development containers

### ISSUE THREAD

**Issue by chriskelly** [skrashevich/double-take#76]
**Describe the bug**
When running `./.develop/docker up`, the api container exits early with `sh: 1: exec: nodemon: not found`

**Version of Double Take**
`1.13.10-SHA7`

**Screenshots**
<img width="595" alt="image" src="https://github.com/skrashevich/double-take/assets/3745832/dc37bba3-1adc-4238-8a22-019e80bcaf1d">

**Hardware**
 - Architecture or platform: intel
 - OS: macOS Ventura

**Comment by skrashevich** [comment]
I don't use devcontainers, and don't update scripts in `.develop`
But I'll be glad if you do PR to fix this problem ;)

**Comment by skrashevich** [comment]
I made a few changes in dbe1774, but I didn't check them

**Comment by chriskelly** [comment]
Seems to have resolved that issue, but exposed a couple others. Thanks for the quick reply btw! I'll see if I can fix these after lunch.
<img width="676" alt="image" src="https://github.com/skrashevich/double-take/assets/3745832/096d7aa6-7c31-4058-b3ec-786ebb8e32ef">

**Comment by chriskelly** [comment]
btw, if you don't use devcontainers, how do you typically manage development?

**Comment by skrashevich** [comment]
> but exposed a couple others

[e1da76c](https://github.com/skrashevich/double-take/commit/e1da76ce2ba1cca7c8724e4bd231457e22866691)
