### ISSUE TITLE
Sometimes getting these 502 errors upon restarting?

### ISSUE THREAD

**Issue by atv2016** [skrashevich/double-take#80]
Is this a http code? Is it getting bad gateway for one of the configured ip's in the config ?

**Comment by atv2016** [comment]
NM i found the add-on url. 
What are the differences between this and the old double take if i may ask ? It seems to run much better/faster in any case.

**Comment by atv2016** [comment]
Also getting a lot of these: error: AxiosError: stream error: timeout of 5000ms exceeded

**Comment by atv2016** [comment]
I seem to have resolved this by uncommenting the opencv_face_required. Seemed the docker host was running at 99% cpu.
I'm running ARCface , the heaviest library but i don't remember having these issues before.

I've been having these issues for a while, maybe i switched it on when i started ARCface and that's what caused the problems. It probably works fine with the default facenet library.

**Comment by skrashevich** [comment]
> Also getting a lot of these: error: AxiosError: stream error: timeout of 5000ms exceeded

Are you use arm64 platform + ai.server detector?

**Comment by atv2016** [comment]
It's resolved, working smooth now! Thanks.
