### ISSUE TITLE
[FEAT] Can we get some of the plugins from Compreface working in double take 

### ISSUE THREAD

**Issue by atv2016** [skrashevich/double-take#82]
**Is your feature request related to a problem? Please describe.**
Would like to see gender and age for example. Not sure if it would interfere with double take, but a few extra lines we should be able to circumvent that and still show these items.

**Describe the solution you'd like**
See: https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md#face-plugins)

Seems the plugins can be active by just passing them in a comma separated list.
**Additional context**

**Comment by skrashevich** [comment]
Where would you like to see these additional labels in the interface?
Describe the use-case when this feature can be helpful

**Comment by linost-xx** [comment]
This is already supported.

detectors:
  compreface:
    url: 
    # recognition api key
    key: 
    # number of seconds before the request times out and is aborted
    timeout: 15
    # minimum required confidence that a recognized face is actually a face
    # value is between 0.0 and 1.0
    det_prob_threshold: 0.8
    # require opencv to find a face before processing with detector
    opencv_face_required: false
    # comma-separated slugs of face plugins
    # https://github.com/exadel-inc/CompreFace/blob/master/docs/Face-services-and-plugins.md)
    face_plugins: gender,age #mask
