### ISSUE TITLE
[BUG] Error loading Double Take on v1.13.11

### ISSUE THREAD

**Issue by townsmcp** [skrashevich/double-take#90]
**Describe the bug**
Load Double Take including previous recognised images

**Version of Double Take**
1.13.11

**Expected behavior**
Interface opens with no errors 

**Screenshots**
![IMG_6474](https://github.com/skrashevich/double-take/assets/14061617/17f94842-5a06-4194-8a9e-082d7b6696b1)

when I click on Config in DT I see the following:
![IMG_6475](https://github.com/skrashevich/double-take/assets/14061617/dea622b1-3deb-4e5f-9113-f81efae86d0f)

**Hardware**
 - HA running in a VM on Proxmox

**Additional context**
HA is supervisor 2023.8.2
OS is 10.4

**Comment by townsmcp** [comment]
I looked at the config of the DT addon and noticed the SECRETS_PATH now looks wrong:
![IMG_6476](https://github.com/skrashevich/double-take/assets/14061617/e898b5db-9b05-4262-acaf-e5173a0fcce1)
However when I change to the correct path (/config/double-take), save and reload DT I still get the same errors shown in original post

**Comment by skrashevich** [comment]
Oh... my mistake, It looks like I incorrectly processed the update from the previous version :(
Try to remove double-take add-on and then install it again.

**Comment by Trebacz** [comment]
I had a slightly different error after the upgrade to 1.13.11. The advice above "Try to remove double-take add-on and then install it again." worked perfect. All my configuration was preserved and it's running fine.

**Comment by buhito81** [comment]
Same issue here, running HAOS Supervised on 2023.8.2.

Unfortunately reinstalling, rebooting, deleting etc didn't resolve this issue for me.

**Comment by AndLindemann** [comment]
Uninstalling and re-installing fixed the 404 errors for me, though one error still remains:

<img width="1440" alt="Bildschirmfoto 2023-08-16 um 09 59 17" src="https://github.com/skrashevich/double-take/assets/4157845/5110b8ba-42e3-4139-8573-b513f573fb6f">

**Comment by townsmcp** [comment]
> Oh... my mistake, It looks like I incorrectly processed the update from the previous version :( Try to remove double-take add-on and then install it again.
> 
> *_PATH options should disappear from the add-on configuration. Paths are now configured in the configuration file of double-take itself

@skrashevich I gave that a try and sadly still get the same errors. 
I also tried the following without success:

- Uninstalling 1.13.11, rebooting HA, installing 1.13.11.
- Restoring backup to 1.13.10, reboot HA, uninstall 1.13.10, install 1.13.11, rebooting HA


None of these worked. The DT config didn’t show the paths though when installing fresh 1.13.11 (rather than upgrading from 1.13.10)

**Comment by Plawasan** [comment]
FWIW, I'm having the same issue but it's apparently not an issue with the addon itself but rather accessing it from HA directly, when I go to http://homeassistant.local:3000/ I can access doubletake, it's processing faces, I can even see the HA entities updating as expected... it's just the Addon GUI that doesn't work.

Same config as OP, latest everything, HA running as a VM on Proxmox.

**Comment by melnikovRV** [comment]
After reinstalling the add-on now works, but there was that old error that was in the old versions of the addon
<img width="457" alt="Снимок экрана 2023-08-16 в 19 58 31" src="https://github.com/skrashevich/double-take/assets/45739282/9356afe8-beee-4638-b2dc-5c30182082ad">

**Comment by jmtatsch** [comment]
I have the same issue as @Plawasan
Maybe this is because I am using NGINX Home Assistant SSL proxy add-on?

**Comment by atv2016** [comment]
Yeah i get this, i have no options part at all though. Mqtt shows a not authorised message.
I thought it was the secrets file as i have secret.yml and secrets.yaml. But adding both does not make a difference.

Seems some sort of authentication error though.

**Comment by atv2016** [comment]
I have uninstalled it and re-installed, not getting mqtt unauthorised messages but still all the 404 messages and the password thing as well (and obviously no matches or training images left anymore).

Can we just revert to the old version if we can't find the bug ?

**Comment by toddstar** [comment]
>  Paths are now configured in the configuration file of double-take itself

What header should they be listed under? Unless I'm blind I can see any references or examples in the docs

**Comment by atv2016** [comment]
So where does one configure this ui -> path option ?
If i look in web inspector i can see it's going to homeassistant.local:8123, that's why all the 404's are appearing. It's not going to port 3000 anymore.

**Comment by luzik** [comment]
I am using docker version without any proxy and I've got:

`request.headers.common is undefind error messages`

**Comment by clowncracker** [comment]
@atv2016 you figure it out?

**Comment by atv2016** [comment]
Nope and there seems to be no movement on this from the current author. Best thing now would be to move back to the old version I guess, but I haven’t had time to do that yet.

It’s really only the front end of the add on, everything else including current automations work fine.
________________________________

**Comment by skrashevich** [comment]
new release 1.13.11.1 must fix this issue (I hope)

**Comment by Plawasan** [comment]
> new release 1.13.11.1 must fix this issue (I hope)

Unfortunately not for me.. Now I get

{"error":"Access denied to IP address: ::ffff:172.30.32.2"}

plus my log is full of these messages.. 

at Function.process_params (/double-take/api/node_modules/express/lib/router/index.js:346:12) at next (/double-take/api/node_modules/express/lib/router/index.js:280:10) at module.exports (/double-take/api/src/middlewares/respond.js:54:3) at newFn (/double-take/api/node_modules/express-async-errors/index.js:16:20) info: Access denied to IP address: ::ffff:127.0.0.1 error: IpDeniedError: Access denied to IP address: ::ffff:127.0.0.1

**Comment by skrashevich** [comment]
v1.13.11.2 will fix this issue

**Comment by luzik** [comment]
It fixed mine issue

**Comment by Plawasan** [comment]
> [v1.13.11.2](https://github.com/skrashevich/double-take/tree/v1.13.11.2) will fix this issue

Success!

**Comment by atv2016** [comment]
Thanks! Fixed. Do we know what the issue was?
________________________________

**Comment by townsmcp** [comment]
@skrashevich I have updated to v1.13.11.2. I can get into DT now, however all trained people are no longer trained. From the drop down I could see most of the names, but not all names previously trained are showing up.
Also, the main problem now is when on the Matches tab no images show and no new events are coming through:
<img width="1359" alt="image" src="https://github.com/skrashevich/double-take/assets/14061617/e0ad4289-3130-4cf8-b64c-95bfb849400d">

Any suggestions of what is going on? When I browse to Config tab, I can see most connections are green apart from Frigate:
<img width="815" alt="image" src="https://github.com/skrashevich/double-take/assets/14061617/f9622091-260b-4a3a-8cc2-6be327977cab">


Also, when I look at DT addon logs, I see the following error:
```
error: Error: connect ECONNREFUSED 192.168.1.158:5000
    at Function.AxiosError.from (/double-take/api/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/double-take/api/node_modules/axios/dist/node/axios.cjs:3016:25)
    at RedirectableRequest.emit (node:events:513:28)
    at ClientRequest.eventHandlers.<computed> (/double-take/api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Finally, are the paths now hard coded or configurable in DT config? For example I want to place the detected images into /config/www/double-take
