### ISSUE TITLE
[BUG] Filtering in matches view doesn't work

### ISSUE THREAD

**Issue by joekerna** [skrashevich/double-take#93]
**Describe the bug**
When I'm in the Matches view, I want to filter for all _unknown_ matches (among other selections).
No matter what I select in the filter section, I always see all the photos (trained, untrained, matched, unmatched,...)

**Version of Double Take**
`1.13.10`

**Expected behavior**
I would expect to select only certain photos, depending on my selection in the filters.

**Screenshots**
![image](https://github.com/skrashevich/double-take/assets/23077594/6247b32f-0078-498c-9bd3-3a1dbf7be3b3)

**Hardware**
 - amd64
 -  Ubuntu 22.04
 - Firefox
 - skrashevich/double-take:latest

**Comment by skrashevich** [comment]
I can't reproduce this bug.
can you provide detailed steps-to-reproduce? (for example, I see that problem images was re-processed before taking screenshot)

**Comment by joekerna** [comment]
I've just updated to the latest docker container and the issue is gone. I don't know what happened last time. It was working on FIrefox Ubuntu 22.04, Android but not on Firefox Windows 10.

I'm glad it's working perfectly now.

Thanks

**Comment by atv2016** [comment]
@skrashevich  Hmm i see this as well. I filtered on unknowns but get all matches. Using 1.13.11.2
