### ISSUE TITLE
[BUG] exec /bin/bash: exec format error

### ISSUE THREAD

**Issue by zamojski** [skrashevich/double-take#95]
**Describe the bug**
Home Assistant Addon fails to start with `exec /bin/bash: exec format error` message in the Logs tab.

It was working for couple of weeks before without any changes in configuration. The only thing that could change is the Home Assistant versions. After noticing the problem I've upgraded to latest version of OS and Core but it didn't help. Reinstallation of addon also didn't solve the issue.

**Version of Double Take**
`1.13.11`

**Expected behavior**
Application starts.

**Hardware**
 - Architecture or platform: raspberry4
 - OS: Home Assistant
 - Docker image (if applicable): skrashevich/double-take:latest

**Comment by skrashevich** [comment]
rasperripi4 runs on arm64 or arm(32) kernel?

**Comment by zamojski** [comment]
Arm64. Meanwhile I've setup a new instance on another machine with amd64 and there's no such issue. It's hard to judge where the problem comes from.
